### ISSUE TITLE
have a look?

### ISSUE THREAD

**Issue by sckott** [sckott/msrgbif#1]
@cboettig @dmcglinn @vijaybarve 

if you have time, could you take a look at the MS on rgbif, first full draft (no abstract yet though). 
- Rmd https://github.com/sckott/msrgbif/blob/gh-pages/manuscript.Rmd
- pdf https://github.com/sckott/msrgbif/blob/gh-pages/manuscript.pdf (download pdf https://github.com/sckott/msrgbif/raw/gh-pages/manuscript.pdf)

if you want to build locally, just clone then run `make`

I copied @cboettig MS template here

if anyone wants to be an author, let me know

Also, I only have plans to put up as a pre-print for now, maybe to a journal, but not really impt. for me.

**Comment by vijaybarve** [comment]
@sckott Great initiative. I was thinking about this for some time but never initiated it. I would be more than happy to contribute and would love to be an author too.

**Comment by sckott** [comment]
Okay, try to get comments/additions/changes back in a few weeks, then iterate from there - not that there's a deadline, but just to get this done and out of the way

**Comment by cboettig** [comment]
Looking over now. A few quick comments:
- [x] spell check etc.  Also some hanging sentences (e.g. `another package, spoccutils`)
- [x] add references for 'well known text'.  
- [x] related to wkt: in the `geometry = ((POLYGON` example, it's not clear to me what these numbers mean.  What are the units? what spatial area is represented by such a polygon?  (same with the bounding box).  It would be more instructive if the polygon in question were some familiar & relevant polygon (e.g. the state of California, for instance).  
- [x] ~ L 166 Hadley uses "tidy data" to refer to data structure itself (e.g. obeys [Codd's 3rd normal form](https://en.wikipedia.org/wiki/Third_normal_form), where each row has "a fact about the key, the whole key, and nothing but the key"), you seem to be using the term to refer more to the print method used by `dplyr`.  
- [x] I think the reader could benefit from more introduction to GBIF itself.  You move very quickly from "individuals are important" to nitty gritty.  I think it would be important to discuss the level of aggregation at which GBIF presents data, and why that is matters.  I find a user needs to have some basic 'schema' or big picture of how a database is organized & what fields it contains before they can do much with it.  
- [ ] it may be beyond your scope here, but it would be really nice to have a sense of what kind of questions people are trying to answer using GBIF, and how they deal with some of the resulting challenges.  For instance, I get the impression it is used as a source of occurrence data -- I want a list of lat/long values for where a given set of species have been observed.  Of course there are a lot of issues that arise in doing this, because the species aren't being randomly sampled from anywhere in space, but collected from areas where they are known to exist, or near where the researcher works, etc.  Using GBIF metadata to tease some of this out seems like an important challenge.

**Comment by sckott** [comment]
> spell check etc.  Also some hanging sentences (e.g. `another package, spoccutils`)

will do, yep, that pkg name has changed too, will get to CRAN soon

> add references for 'well known text'.  

thx, will add some references

> related to wkt: in the `geometry = ((POLYGON` example, it's not clear to me what these numbers mean.  What are the units? what spatial area is represented by such a polygon?  (same with the bounding box).  It would be more instructive if the polygon in question were some familiar & relevant polygon (e.g. the state of California, for instance).  

The numbers are lat/long coordinate pairs, forming a polygon, e.g, see first and last, should be the same. WKT polygons is what GBIF accepts for geometry searches.  We do try to make it easier in the `spocc` package by allowing users to pass in spatial objects (e.g., `SpatialPolygon`), and bounding boxes. Within `rgbif` we accept WKT string or bounding box - could add spatial objects as well, but don't want to introduce new dependencies

> ~ L 166 Hadley uses "tidy data" to refer to data structure itself (e.g. obeys [Codd's 3rd normal form](https://en.wikipedia.org/wiki/Third_normal_form), where each row has "a fact about the key, the whole key, and nothing but the key"), you seem to be using the term to refer more to the print method used by `dplyr`.  

right, good pt, will change wording there. 

> I think the reader could benefit from more introduction to GBIF itself.  You move very quickly from "individuals are important" to nitty gritty.  I think it would be important to discuss the level of aggregation at which GBIF presents data, and why that is matters.  I find a user needs to have some basic 'schema' or big picture of how a database is organized & what fields it contains before they can do much with it.  

good pt, will lay out how GBIF is organized, and how to help users understand how to interact with it

> it may be beyond your scope here, but it would be really nice to have a sense of what kind of questions people are trying to answer using GBIF, and how they deal with some of the resulting challenges.  For instance, I get the impression it is used as a source of occurrence data -- I want a list of lat/long values for where a given set of species have been observed.  Of course there are a lot of issues that arise in doing this, because the species aren't being randomly sampled from anywhere in space, but collected from areas where they are known to exist, or near where the researcher works, etc.  Using GBIF metadata to tease some of this out seems like an important challenge.  

There are lots of papers using GBIF data. GBIF collects some, and we have those collected that use this client.  So that should be easy to get a sense for questions folks are asking.  Right, would be great to pinpoint the most common questions, and think about what can be done to help make it easy to get answers to those questions given the limitations of the data, etc. On topic of whether it's within scope - don't know. Could be if it's just a brief section, but could balloon into something larger.

**Comment by sckott** [comment]
feedback from Ross here https://discuss.ropensci.org/t/feedback-on-rgbif-manuscript/290/3

**Comment by sckott** [comment]
carls comment about questinos asked in #5 now
